### ISSUE TITLE
panic when %change-focus after creating and syncing new ship

### ISSUE THREAD

**Issue by hosted-fornet** [uqbar-dao/ziggurat-ui#164]
I created a new ship in project A. I synced that ship. Then I swtiched project to project B. The status changed to PANIC. It seems there is some weirdness going on here. I'll investigate on the backend as well.

**Comment by 0x70b1a5** [comment]
Panic isn't a real status as you might have guessed, it just gets
triggered under certain circumstances - currently I think that the
only case is when a poke gets rejected due to "setting up new
project". I think that's the only time that it would make sense to ask
the user to send a %cis-panic (might be wrong though). Maybe panic is
too strong a term.

**Comment by hosted-fornet** [comment]
Ah, ok, that makes sense.
